services:

  broker1:
    build:
      context: .
      args:
        TARGET: broker
    container_name: broker-1
    ports:
      - "9000:9000"
    environment:
      - BROKER_ID=1
      - BROKER_PORT=:9000
      - MY_ADDR=${ADDR_BROKER_1}
      - SEED_ADDRS=${ADDR_BROKER_2},${ADDR_BROKER_3},${ADDR_BROKER_4}
    networks:
      - ormuz-net

  broker2:
    build:
      context: .
      args:
        TARGET: broker
    container_name: broker-2
    ports:
      - "9001:9000"
    environment:
      - BROKER_ID=2
      - BROKER_PORT=:9000
      - MY_ADDR=${ADDR_BROKER_2}
      - SEED_ADDRS=${ADDR_BROKER_1},${ADDR_BROKER_3},${ADDR_BROKER_4}
    networks:
      - ormuz-net

  broker3:
    build:
      context: .
      args:
        TARGET: broker
    container_name: broker-3
    ports:
      - "9002:9000"
    environment:
      - BROKER_ID=3
      - BROKER_PORT=:9000
      - MY_ADDR=${ADDR_BROKER_3}
      - SEED_ADDRS=${ADDR_BROKER_2},${ADDR_BROKER_1},${ADDR_BROKER_4}
    networks:
      - ormuz-net

  broker4:
    build:
      context: .
      args:
        TARGET: broker
    container_name: broker-4
    ports:
      - "9002:9000"
    environment:
      - BROKER_ID=4
      - BROKER_PORT=:9000
      - MY_ADDR=${ADDR_BROKER_4}
      - SEED_ADDRS=${ADDR_BROKER_2},${ADDR_BROKER_3},${ADDR_BROKER_1}
    networks:
      - ormuz-net

  sensor_setor_1:
    build:
      context: .
      args:
        TARGET: sensor
    container_name: sensor-1
    environment:
      - BROKER_ADDRS=${ADDR_BROKER_1},${ADDR_BROKER_2},${ADDR_BROKER_3},${ADDR_BROKER_4}
      - SETOR_ID=1
    networks:
      - ormuz-net

  sensor_setor_2:
    build:
      context: .
      args:
        TARGET: sensor
    container_name: sensor-2
    environment:
      - BROKER_ADDRS=${ADDR_BROKER_1},${ADDR_BROKER_2},${ADDR_BROKER_3},${ADDR_BROKER_4}
      - SETOR_ID=2
    networks:
      - ormuz-net


  sensor_setor_3:
    build:
      context: .
      args:
        TARGET: sensor
    container_name: sensor-3
    environment:
      - BROKER_ADDRS=${ADDR_BROKER_1},${ADDR_BROKER_2},${ADDR_BROKER_3},${ADDR_BROKER_4}
      - SETOR_ID=3
    networks:
      - ormuz-net


  sensor_setor_4:
    build:
      context: .
      args:
        TARGET: sensor
    container_name: sensor-4
    environment:
      - BROKER_ADDRS=${ADDR_BROKER_1},${ADDR_BROKER_2},${ADDR_BROKER_3},${ADDR_BROKER_4}
      - SETOR_ID=4
    networks:
      - ormuz-net


  drone_alpha:
    build:
      context: .
      args:
        TARGET: drone
    container_name: drone-alpha
    environment:
      - DRONE_ID=ALPHA
      - BROKER_ADDRS=${ADDR_BROKER_1},${ADDR_BROKER_2},${ADDR_BROKER_3},${ADDR_BROKER_4}
    networks:
      - ormuz-net

  drone_bravo:
    build:
      context: .
      args:
        TARGET: drone
    container_name: drone-bravo
    environment:
      - DRONE_ID=BRAVO
      - BROKER_ADDRS=${ADDR_BROKER_1},${ADDR_BROKER_2},${ADDR_BROKER_3},${ADDR_BROKER_4}
    networks:
      - ormuz-net

  drone_beta:
    build:
      context: .
      args:
        TARGET: drone
    container_name: drone-beta
    environment:
      - DRONE_ID=BRAVO
      - BROKER_ADDRS=${ADDR_BROKER_1},${ADDR_BROKER_2},${ADDR_BROKER_3},${ADDR_BROKER_4}
    networks:
      - ormuz-net


  # -------------------------------------------------------
  # CLIENTE OPERADOR (terminal interativo)
  # Uso: docker compose run --rm cliente
  # -------------------------------------------------------
  cliente:
    build:
      context: .
      args:
        TARGET: cliente
    container_name: cliente
    stdin_open: true
    tty: true
    environment:
      - BROKER_ADDRS=${ADDR_BROKER_1},${ADDR_BROKER_2},${ADDR_BROKER_3}
    networks:
      - ormuz-net

  # -------------------------------------------------------
  # SUITE DE TESTES AUTOMATIZADOS
  # Uso: docker compose run --rm testes
  # -------------------------------------------------------
  testes:
    build:
      context: .
      args:
        TARGET: testes
    container_name: testes
    environment:
      - BROKER_ADDRS=${ADDR_BROKER_1},${ADDR_BROKER_2},${ADDR_BROKER_3}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ormuz-net

networks:
  ormuz-net:
    driver: bridge